---
git:
  depth: 10
language: node_js

node_js:
  - "6"
  - "4"

sudo: required # Until Yarn repo is added to apt-source-whitelist

addons:
  apt:
    packages:
      - git

branches:
  only:
  - master
  - /^.*-stable$/

cache:
  # Yarn installed with Travis breaks in Node 4, see https://travis-ci.org/yarnpkg/yarn/jobs/215947941
  yarn: false

env:
  matrix:
    - TEST_TYPE="build-dist"
    - TEST_TYPE="check-lockfile"
    - TEST_TYPE="lint"
    - TEST_TYPE="test-ci -- -- --maxWorkers 3"

matrix:
  exclude:
    - env: TEST_TYPE="build-dist"
      node_js: "4"
    - env: TEST_TYPE="check-lockfile"
      node_js: "4"
    - env: TEST_TYPE="lint"
      node_js: "4"
  include:
    - os: osx
      node_js: "6"
      env: TEST_TYPE="test-ci"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/bootstrap-env-ubuntu.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      RAMDISK_SIZE=390;
      RAMDISK_SECTORS=$(( $RAMDISK_SIZE * 1024 * 1024 / 512 ));
      RAMDISK=$(hdiutil attach -nomount ram://$RAMDISK_SECTORS);
      newfs_hfs -v yarn_ramfs $RAMDISK;
      mkdir -p /tmp/ramfs;
      mount -t hfs -o nobrowse $RAMDISK /tmp/ramfs;
      rsync -a ./__tests__/ /tmp/ramfs;
      umount /tmp/ramfs;
      mount -t hfs -o nobrowse $RAMDISK ./__tests__;
      export TMPDIR="$(pwd)/__tests__/.tmp";
      mkdir -p $TMPDIR;
    fi

os:
  - linux

script: travis_retry yarn $TEST_TYPE
